import { Event } from '../types/index';

// Derived from PDF Page 2 (16 dates to Maxwell Mentorship)
export const EVENTS_DATA_SEED: Event[] = [
  // --- SERIES CONTAINER ---
  { 
    id: 'SERIES-2026', 
    name: 'Maxwell Mentorship 2026 (16 Sessions)', 
    date: '2026-01-08', 
    location: 'Hybrid (Jakarta & Online)', 
    locationMode: 'HYBRID',
    attendees: 0, 
    capacity: 500, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'CONTAINER', 
    creditTags: ['BUNDLE_2026', 'MLCT_FULL'],
    admissionPolicy: 'PRE_BOOKED',
    parentEventId: undefined
  },

  // --- 2026 SESSIONS (A1 - A16) ---
  { 
    id: 'EVT-26-A1', 
    parentEventId: 'SERIES-2026', 
    classId: 'A1', 
    name: 'The Greatest Story Ever Told (Intentional Living)', 
    date: '2026-01-08', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A1'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A2', 
    parentEventId: 'SERIES-2026', 
    classId: 'A2', 
    name: 'Dream Tester (Put Your Dream To The Test)', 
    date: '2026-01-09', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A2'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A3', 
    parentEventId: 'SERIES-2026', 
    classId: 'A3', 
    name: 'Awaken the Leader Within (Developing the Leader Within 2.0)', 
    date: '2026-01-10', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A3'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A4', 
    parentEventId: 'SERIES-2026', 
    classId: 'A4', 
    name: 'Movement of Influence (Becoming A Person Of Influence)', 
    date: '2026-02-07', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A4'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A5', 
    parentEventId: 'SERIES-2026', 
    classId: 'A5', 
    name: 'Movement of Integrity (High Road Leadership)', 
    date: '2026-02-28', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A5'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A6', 
    parentEventId: 'SERIES-2026', 
    classId: 'A6', 
    name: 'Movement of Impact (Change Your World)', 
    date: '2026-04-18', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A6'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A7', 
    parentEventId: 'SERIES-2026', 
    classId: 'A7', 
    name: 'Movement of Interaction (Everyone Communicates, Few Connect)', 
    date: '2026-05-23', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A7'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A8', 
    parentEventId: 'SERIES-2026', 
    classId: 'A8', 
    name: 'E-xpand Your Territory (15 Invaluable Laws of Growth)', 
    date: '2026-06-11', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A8'],
    admissionPolicy: 'PRE_BOOKED'
  },
  
  // NEW FROM PDF PAGE 2
  { 
    id: 'EVT-26-A9', 
    parentEventId: 'SERIES-2026', 
    classId: 'A9', 
    name: 'X-factor of Life (Leading Through Crisis)', 
    date: '2026-06-12', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A9'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A10', 
    parentEventId: 'SERIES-2026', 
    classId: 'A10', 
    name: 'P-ursuit of Life (Sometimes You Win, Sometimes You Learn)', 
    date: '2026-06-13', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A10'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A11', 
    parentEventId: 'SERIES-2026', 
    classId: 'A11', 
    name: 'E-ngineering of Success (How to be a REAL Success)', 
    date: '2026-08-29', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A11'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A12', 
    parentEventId: 'SERIES-2026', 
    classId: 'A12', 
    name: 'Core Strength of Leadership (Leadership Gold)', 
    date: '2026-09-26', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A12'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A13', 
    parentEventId: 'SERIES-2026', 
    classId: 'A13', 
    name: 'Template of Business Leadership (DT1)', 
    date: '2026-10-23', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A13'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A14', 
    parentEventId: 'SERIES-2026', 
    classId: 'A14', 
    name: 'Template of Business Leadership (DT2)', 
    date: '2026-10-24', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A14'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A15', 
    parentEventId: 'SERIES-2026', 
    classId: 'A15', 
    name: 'Template of Business Leadership (DT3)', 
    date: '2026-10-30', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A15'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-26-A16', 
    parentEventId: 'SERIES-2026', 
    classId: 'A16', 
    name: 'Template of Business Leadership (DT4)', 
    date: '2026-10-31', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 200, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SESSION', 
    creditTags: ['ACCESS_A16'],
    admissionPolicy: 'PRE_BOOKED'
  },

  // --- 2025 CURRENT/PAST EVENTS (For Context) ---
  { 
    id: 'EVT-25-DTR', 
    name: 'DTR: Pursue Excellence, Dump Perfection', 
    date: '2025-04-21', 
    location: 'Jakarta', 
    locationMode: 'OFFLINE',
    attendees: 150, 
    capacity: 200, 
    revenue: 52500000, 
    status: 'Upcoming', 
    type: 'SOLO', 
    creditTags: ['DTR_CREDIT'],
    admissionPolicy: 'PRE_BOOKED'
  },
  { 
    id: 'EVT-25-IMC', 
    classId: 'IMC25', 
    name: 'International Maxwell Conference (IMC) Jakarta', 
    date: '2025-09-01', 
    location: 'Jakarta Ballroom', 
    locationMode: 'OFFLINE',
    attendees: 0, 
    capacity: 1500, 
    revenue: 0, 
    status: 'Upcoming', 
    type: 'SOLO', 
    creditTags: ['ACCESS_IMC_25'],
    admissionPolicy: 'PRE_BOOKED'
  },
  {
    id: 'EVT-25-CCS',
    name: 'Capacity Catalyst Summit', 
    date: '2025-11-15',
    location: 'Jakarta',
    locationMode: 'OFFLINE',
    attendees: 0,
    capacity: 500,
    revenue: 0,
    status: 'Upcoming', 
    type: 'SOLO',
    creditTags: ['ACCESS_CCS'],
    admissionPolicy: 'PRE_BOOKED'
  }
];