
import React, { useState, useEffect } from 'react';
import { ContentService } from '../services/contentService';
import { ContentPost, ContentType, ContentStatus } from '../types/index';
import { STORE_PRODUCTS } from '../constants';
import { AIService } from '../services/aiService';
import { useToast } from '../context/ToastContext';
import { 
    LayoutTemplate, PenTool, BarChart3, Plus, Search, 
    Edit3, Save, Sparkles, Image as ImageIcon, Link
} from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import RichTextEditor from './communication/RichTextEditor'; // REUSED COMPONENT

const CMSAdmin: React.FC = () => {
    const { showToast } = useToast();
    const [posts, setPosts] = useState<ContentPost[]>([]);
    const [activeTab, setActiveTab] = useState<'LIST' | 'EDITOR' | 'CALENDAR' | 'STATS'>('LIST');

    // Editor State
    const [editingPost, setEditingPost] = useState<Partial<ContentPost>>({});
    const [isAiGenerating, setIsAiGenerating] = useState(false);
    const [aiPrompt, setAiPrompt] = useState('');

    useEffect(() => {
        loadContent();
    }, []);

    const loadContent = async () => {
        const data = await ContentService.getAllContent();
        setPosts(data);
    };

    const handleNewPost = () => {
        setEditingPost({
            title: '',
            body: '',
            type: 'ARTICLE',
            status: 'DRAFT',
            publishDate: new Date().toISOString().slice(0, 16), // datetime-local format
            author: 'Admin'
        });
        setActiveTab('EDITOR');
    };

    const handleEditPost = (post: ContentPost) => {
        setEditingPost({ ...post, publishDate: post.publishDate.slice(0, 16) });
        setActiveTab('EDITOR');
    };

    const handleSave = async () => {
        if (!editingPost.title) {
            showToast('Title is required', 'error');
            return;
        }

        if (editingPost.id) {
            await ContentService.updateContent(editingPost.id, editingPost);
            showToast('Content updated', 'success');
        } else {
            await ContentService.createContent(editingPost);
            showToast('Content created', 'success');
        }
        await loadContent();
        setActiveTab('LIST');
    };

    const handleAiGenerate = async () => {
        if (!aiPrompt) return;
        setIsAiGenerating(true);
        try {
            const product = STORE_PRODUCTS.find(p => p.id === editingPost.linkedProductId);
            const result = await AIService.generateContent(
                aiPrompt, 
                editingPost.type as 'ARTICLE' | 'AD' || 'ARTICLE',
                product
            );
            setEditingPost(prev => ({ ...prev, title: result.title, body: result.body }));
            showToast('Content generated by AI', 'success');
        } catch (e) {
            showToast('AI Generation failed', 'error');
        } finally {
            setIsAiGenerating(false);
        }
    };

    const formatIDR = (num: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' }).format(num);

    // --- VIEWS ---

    const renderList = () => (
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50">
                <div className="relative w-64">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} />
                    <input type="text" placeholder="Search content..." className="w-full pl-9 pr-4 py-2 text-sm border rounded-lg outline-none focus:border-blue-500" />
                </div>
                <button onClick={handleNewPost} className="bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-bold flex items-center hover:bg-blue-700">
                    <Plus size={16} className="mr-2" /> Create Content
                </button>
            </div>
            <div className="overflow-x-auto">
                <table className="w-full text-left text-sm">
                    <thead className="bg-slate-50 text-slate-500 font-medium">
                        <tr>
                            <th className="px-6 py-4">Title</th>
                            <th className="px-6 py-4">Type</th>
                            <th className="px-6 py-4">Status</th>
                            <th className="px-6 py-4">Schedule</th>
                            <th className="px-6 py-4">Engagement</th>
                            <th className="px-6 py-4 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                        {posts.map(post => (
                            <tr key={post.id} className="hover:bg-slate-50">
                                <td className="px-6 py-4">
                                    <div className="font-bold text-slate-900">{post.title}</div>
                                    <div className="text-xs text-slate-500 truncate max-w-[200px]">{post.slug}</div>
                                </td>
                                <td className="px-6 py-4">
                                    <span className={`text-[10px] font-bold px-2 py-1 rounded ${post.type === 'ADVERTISEMENT' ? 'bg-amber-100 text-amber-700' : 'bg-blue-100 text-blue-700'}`}>
                                        {post.type}
                                    </span>
                                </td>
                                <td className="px-6 py-4">
                                    <span className={`flex items-center gap-1.5 text-xs font-medium ${post.status === 'PUBLISHED' ? 'text-green-600' : 'text-slate-500'}`}>
                                        <span className={`w-2 h-2 rounded-full ${post.status === 'PUBLISHED' ? 'bg-green-500' : 'bg-slate-400'}`}></span>
                                        {post.status}
                                    </span>
                                </td>
                                <td className="px-6 py-4 text-xs text-slate-500">
                                    {new Date(post.publishDate).toLocaleDateString()}
                                </td>
                                <td className="px-6 py-4">
                                    <div className="flex gap-3 text-xs">
                                        <span title="Views">👁️ {post.stats.views}</span>
                                        <span title="Clicks">🖱️ {post.stats.clicks}</span>
                                        <span title="Sales" className="text-green-600 font-bold">💲 {post.stats.conversions}</span>
                                    </div>
                                </td>
                                <td className="px-6 py-4 text-right">
                                    <button onClick={() => handleEditPost(post)} className="text-blue-600 hover:bg-blue-50 p-2 rounded transition-colors"><Edit3 size={16}/></button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );

    const renderEditor = () => (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 h-[calc(100vh-200px)]">
            {/* Left: Input */}
            <div className="lg:col-span-2 flex flex-col gap-4 overflow-hidden">
                <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm flex flex-col h-full">
                    <div className="space-y-4 mb-4 flex-shrink-0">
                        <div>
                            <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Headline</label>
                            <input 
                                type="text" 
                                className="w-full text-xl font-bold p-2 border-b-2 border-slate-200 focus:border-blue-500 outline-none placeholder:text-slate-300"
                                placeholder="Enter catchy headline..."
                                value={editingPost.title}
                                onChange={e => setEditingPost({...editingPost, title: e.target.value})}
                            />
                        </div>
                        
                        {/* AI Prompt Area */}
                        <div className="bg-indigo-50 p-4 rounded-lg border border-indigo-100 flex gap-2 items-center">
                            <Sparkles className="text-indigo-600 shrink-0" size={20} />
                            <input 
                                type="text" 
                                className="flex-1 bg-white border border-indigo-200 rounded px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-300"
                                placeholder="AI Co-Pilot: Describe what you want to write about..."
                                value={aiPrompt}
                                onChange={e => setAiPrompt(e.target.value)}
                                onKeyDown={e => e.key === 'Enter' && handleAiGenerate()}
                            />
                            <button 
                                onClick={handleAiGenerate}
                                disabled={isAiGenerating || !aiPrompt}
                                className="bg-indigo-600 text-white px-4 py-2 rounded text-xs font-bold hover:bg-indigo-700 disabled:opacity-50"
                            >
                                {isAiGenerating ? 'Writing...' : 'Generate'}
                            </button>
                        </div>
                    </div>

                    <div className="flex-1 min-h-0 border border-slate-200 rounded-lg overflow-hidden">
                        {/* RICH TEXT EDITOR INTEGRATION */}
                        <RichTextEditor 
                            value={editingPost.body || ''}
                            onChange={(val) => setEditingPost({...editingPost, body: val})}
                            availableVariables={['member_name', 'join_date', 'product_name']} // Context vars for CMS
                        />
                    </div>
                </div>
            </div>

            {/* Right: Settings */}
            <div className="space-y-4 overflow-y-auto">
                <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm space-y-4">
                    <h3 className="font-bold text-slate-800 border-b border-slate-100 pb-2">Publishing</h3>
                    
                    <div>
                        <label className="block text-xs font-bold text-slate-500 mb-1">Status</label>
                        <select 
                            className="w-full p-2 border border-slate-200 rounded text-sm"
                            value={editingPost.status}
                            onChange={e => setEditingPost({...editingPost, status: e.target.value as ContentStatus})}
                        >
                            <option value="DRAFT">Draft</option>
                            <option value="SCHEDULED">Scheduled</option>
                            <option value="PUBLISHED">Published</option>
                            <option value="ARCHIVED">Archived</option>
                        </select>
                    </div>

                    <div>
                        <label className="block text-xs font-bold text-slate-500 mb-1">Publish Date</label>
                        <input 
                            type="datetime-local" 
                            className="w-full p-2 border border-slate-200 rounded text-sm"
                            value={editingPost.publishDate}
                            onChange={e => setEditingPost({...editingPost, publishDate: e.target.value})}
                        />
                    </div>

                    <div>
                        <label className="block text-xs font-bold text-slate-500 mb-1">Unpublish Date (Optional)</label>
                        <input 
                            type="datetime-local" 
                            className="w-full p-2 border border-slate-200 rounded text-sm"
                            value={editingPost.unpublishDate || ''}
                            onChange={e => setEditingPost({...editingPost, unpublishDate: e.target.value})}
                        />
                    </div>
                </div>

                <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm space-y-4">
                    <h3 className="font-bold text-slate-800 border-b border-slate-100 pb-2 flex items-center">
                        <Link size={16} className="mr-2"/> Commercial Link
                    </h3>
                    <p className="text-xs text-slate-500">Attach a product card to this content to drive sales.</p>
                    
                    <div>
                        <label className="block text-xs font-bold text-slate-500 mb-1">Linked Product</label>
                        <select 
                            className="w-full p-2 border border-slate-200 rounded text-sm"
                            value={editingPost.linkedProductId || ''}
                            onChange={e => setEditingPost({...editingPost, linkedProductId: e.target.value})}
                        >
                            <option value="">-- None --</option>
                            {STORE_PRODUCTS.map(p => (
                                <option key={p.id} value={p.id}>{p.title}</option>
                            ))}
                        </select>
                    </div>

                    {editingPost.linkedProductId && (
                        <div>
                            <label className="block text-xs font-bold text-slate-500 mb-1">CTA Label</label>
                            <input 
                                type="text"
                                className="w-full p-2 border border-slate-200 rounded text-sm"
                                placeholder="e.g. Buy Now"
                                value={editingPost.ctaLabel}
                                onChange={e => setEditingPost({...editingPost, ctaLabel: e.target.value})}
                            />
                        </div>
                    )}
                </div>

                <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm space-y-4">
                    <h3 className="font-bold text-slate-800 border-b border-slate-100 pb-2">Meta Info</h3>
                    <div>
                        <label className="block text-xs font-bold text-slate-500 mb-1">Type</label>
                        <div className="flex gap-2">
                            {['ARTICLE', 'ADVERTISEMENT', 'NEWS'].map(t => (
                                <button 
                                    key={t}
                                    onClick={() => setEditingPost({...editingPost, type: t as ContentType})}
                                    className={`flex-1 py-1 text-[10px] font-bold rounded border ${editingPost.type === t ? 'bg-blue-600 text-white border-blue-600' : 'bg-slate-50 text-slate-600 border-slate-200'}`}
                                >
                                    {t.substring(0,3)}
                                </button>
                            ))}
                        </div>
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-slate-500 mb-1">Image URL</label>
                        <div className="flex gap-2">
                            <input 
                                type="text" 
                                className="flex-1 p-2 border border-slate-200 rounded text-xs"
                                value={editingPost.imageUrl || ''}
                                onChange={e => setEditingPost({...editingPost, imageUrl: e.target.value})}
                                placeholder="https://..."
                            />
                            <div className="w-8 h-8 bg-slate-100 rounded flex items-center justify-center border border-slate-200">
                                <ImageIcon size={14} className="text-slate-400"/>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="flex gap-3 pt-2">
                    <button onClick={() => setActiveTab('LIST')} className="flex-1 py-2 border border-slate-300 rounded-lg text-sm text-slate-600 font-bold hover:bg-slate-50">Cancel</button>
                    <button onClick={handleSave} className="flex-[2] py-2 bg-slate-900 text-white rounded-lg text-sm font-bold hover:bg-slate-800 shadow-lg flex items-center justify-center">
                        <Save size={16} className="mr-2" /> Save Content
                    </button>
                </div>
            </div>
        </div>
    );

    const renderStats = () => {
        const data = posts.map(p => ({
            name: p.title.substring(0, 15) + '...',
            views: p.stats.views,
            revenue: p.stats.revenueAttributed / 1000000 // In Millions
        })).sort((a,b) => b.views - a.views).slice(0, 10);

        return (
            <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                    <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                        <div className="text-xs font-bold text-slate-500 uppercase">Total Views</div>
                        <div className="text-3xl font-bold text-slate-900 mt-1">{posts.reduce((a,b) => a + b.stats.views, 0).toLocaleString()}</div>
                    </div>
                    <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                        <div className="text-xs font-bold text-slate-500 uppercase">Total Shares</div>
                        <div className="text-3xl font-bold text-blue-600 mt-1">{posts.reduce((a,b) => a + b.stats.shares, 0).toLocaleString()}</div>
                    </div>
                    <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                        <div className="text-xs font-bold text-slate-500 uppercase">Link Clicks</div>
                        <div className="text-3xl font-bold text-purple-600 mt-1">{posts.reduce((a,b) => a + b.stats.clicks, 0).toLocaleString()}</div>
                    </div>
                    <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                        <div className="text-xs font-bold text-slate-500 uppercase">Attributed Rev</div>
                        <div className="text-3xl font-bold text-green-600 mt-1">{formatIDR(posts.reduce((a,b) => a + b.stats.revenueAttributed, 0))}</div>
                    </div>
                </div>

                <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                    <h3 className="font-bold text-slate-800 mb-6">Top Content Performance</h3>
                    <div className="h-80">
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={data}>
                                <XAxis dataKey="name" tick={{fontSize: 10}} />
                                <YAxis yAxisId="left" orientation="left" stroke="#3b82f6" />
                                <YAxis yAxisId="right" orientation="right" stroke="#10b981" />
                                <Tooltip />
                                <Bar yAxisId="left" dataKey="views" fill="#3b82f6" name="Views" radius={[4,4,0,0]} />
                                <Bar yAxisId="right" dataKey="revenue" fill="#10b981" name="Rev (M)" radius={[4,4,0,0]} />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>
            </div>
        );
    };

    return (
        <div className="p-6 max-w-7xl mx-auto h-[calc(100vh-64px)] flex flex-col animate-fade-in relative">
            <div className="flex flex-col md:flex-row justify-between items-end mb-6 gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-slate-900 flex items-center">
                        <LayoutTemplate className="mr-3 text-blue-600" /> Content Intelligence
                    </h1>
                    <p className="text-slate-500 mt-1">Manage public portal, ads, and track content ROI.</p>
                </div>
                <div className="flex bg-slate-100 p-1 rounded-lg">
                    <button onClick={() => setActiveTab('LIST')} className={`px-4 py-2 text-sm font-medium rounded-md transition-all flex items-center ${activeTab === 'LIST' ? 'bg-white shadow text-blue-700' : 'text-slate-500'}`}>
                        <LayoutTemplate size={16} className="mr-2"/> All Content
                    </button>
                    <button onClick={() => setActiveTab('EDITOR')} className={`px-4 py-2 text-sm font-medium rounded-md transition-all flex items-center ${activeTab === 'EDITOR' ? 'bg-white shadow text-blue-700' : 'text-slate-500'}`}>
                        <PenTool size={16} className="mr-2"/> Editor
                    </button>
                    <button onClick={() => setActiveTab('STATS')} className={`px-4 py-2 text-sm font-medium rounded-md transition-all flex items-center ${activeTab === 'STATS' ? 'bg-white shadow text-blue-700' : 'text-slate-500'}`}>
                        <BarChart3 size={16} className="mr-2"/> Analytics
                    </button>
                </div>
            </div>

            <div className="flex-1 overflow-hidden">
                {activeTab === 'LIST' && renderList()}
                {activeTab === 'EDITOR' && renderEditor()}
                {activeTab === 'STATS' && renderStats()}
            </div>
        </div>
    );
};

export default CMSAdmin;
